### PR TITLE
Enhance Pre-Commit Hooks and Improved Error Handling

### PR DESCRIPTION
**Pull request by l50**
# Proposed Changes

Introduce a pre-commit hook for appending "Authored-by" to commit messages, add shfmt pre-commit hook for parameter control, enhance error handling in existing PC scripts, and further refine the hook functionalities.

## Related Issue(s)

N/A

## Description of Changes

- Initially introduced a pre-commit hook for appending "Authored-by" to commit messages.
- Enhanced error handling for situations where `user.name` and `user.email` are not configured.
- Refactor the `check-underscores-in-name` script to use a while loop for reading filenames, enhancing compatibility with filenames with spaces or special characters.
- Introduced conditions in the same script to differentiate YAML files and directories and added more informative echo statements.
- Ensure file exists before renaming in the `check-underscores-in-name` script.
- Added a new script to run Bats tests on all `.bats` files.
- Integrated a shell formatter (`shfmt`) to format shell scripts, excluding those in the `templates/` directory.
- Enhanced the Bats test for checking filenames by splitting the checks for existence and staging of files and provided improved debug output.
- Updated `.pre-commit-config.yaml` to include the new hooks for `shfmt` and Bats testing alongside the original changes for the "Authored-by" append feature.

## Testing

1. Made changes to the repository.
2. Attempted a commit without `user.name` and `user.email` configured, observed a helpful error message prompting configuration.
3. Configured `user.name` and `user.email` as prompted.
4. Committed again, observed "Authored-by" appended to the commit message.
5. Made additional changes to introduce filenames with spaces and underscores, and tested the refined `check-underscores-in-name` script.
6. Ran the new Bats test script and verified the proper handling and output of file renaming.

## Documentation

Updated the `.pre-commit-config.yaml` to reflect the addition of the new hooks and refinements to existing ones.

## Screenshots/GIFs (optional)

N/A

## Checklist

- [x] Ran `mage runprecommit` locally and fixed any issues that arose.
- [x] Curated the commits to be legible and easy to read and understand.
- [x] 🚀

### CODE REVIEW

**Comment by d3sch41n** [comment]
What does `Authored-by` give us relative to the default metadata added by github with merging PRs, such as:

```
commit ca0aec0a461096f5301591f266285f3253136c77 (HEAD -> main, tag: v1.0.5, origin/main, origin/HEAD)
Author: Sam Manzer <smanzer@meta.com>
```

**Comment by l50** [comment]
> What does `Authored-by` give us relative to the default metadata added by github with merging PRs, such as:
> 
> ```
> commit ca0aec0a461096f5301591f266285f3253136c77 (HEAD -> main, tag: v1.0.5, origin/main, origin/HEAD)
> Author: Sam Manzer <smanzer@meta.com>
> ```

The Authored-by line was introduced with the intention of providing an additional layer of recognition for contributors, ensuring that their contributions are properly acknowledged, especially if there were any discrepancies in their Git configurations. That said, it is redundant, so I can remove it from the PR if you'd prefer.

**Comment by d3sch41n** [comment]
Let's discuss pre-commit state with the team out-of-band prior to merging  - I recently helped @cedowens get his pre-commit dialed in for his first major contribution (https://github.com/facebookincubator/ForgeArmory/pull/24) and it was quite onerous, I am concerned about the impact on new contributors if the footprint continues to expand. Can revisit this after that discussion. I've set up a call.

**Comment by l50** [comment]
@d3sch41n added your requested changes from the call to the dev doc. Where did we land on the authored-by PC? Do you want me to remove it from this PR to land?

**Review by d3sch41n — APPROVED** [review]
I'm cool with rolling forward to experiment with this, subject to trial process documented in docs/ttp-dev.md (thanks for adding docs) - approved

**Pull request merged**
