### PR TITLE
Added Tactic TA0043 Reconnaissance with procedure T1595.001 Active Scanning: Scan IP Blocks

### PR DESCRIPTION
**Pull request by sw8y**
# Proposed Changes

Created a TTP for scanning IP blocks using the Nmap utility. This TTP will check the OS of the computer, then confirm that the appropriate package manager is also installed. If confirmed, the system will be checked to see if nmap is installed and install it if not. 

## Related Issue(s)

No issues identified.

## Testing

1. Verified the results of "uname" on the local system.
2. Run TTP with nmap installed to verify functionality.
3. Run TTP without nmap insatlled to verify install.
4. Run TTP without port list to verify default ports are scanned.
5. Run TTP with port list to verify that the provided list of ports are scanned.
6. Run TTP with cleanup option set to false to verify that nmap is not uninstalled.
7. Run TTP with cleanup option set to true to verify that nmap is uninstalled.

## Documentation

README.md has been updated to reflect what this TTP does and how it operates.

## Checklist

- [x] Ran `mage runprecommit` locally and fixed any issues that arose.
- [x] Curated your commit(s) so they are legible and easy to read and understand.
- [x] 🚀

### CODE REVIEW

**Comment by d3sch41n** [comment]
Thanks so much for the contribution! I'm hopping out on vacation until Tuesday so unfortunately I'll need to wait till then for a detailed review, at which point I can help with the pre-commit hook (though of course @l50 may hop in beforehand) - but before I leave just wanted to say that we really appreciate the addition and look forward to collaborating in the near future!

**Comment by l50** [comment]
Hey @sw8y! Did you run mage precommit before submitting the PR?

Additionally, what are the empty placeholder files for?

**Comment by l50** [comment]
I'm going to create a proposal for directory layout next week and will post an RFC for feedback from the community. 

For now, if you can remove the directories with solely placeholders, we can land this bad boy :)

**Comment by sw8y** [comment]
My bad for the late reply! Working on this now :)

**Comment by sw8y** [comment]
For those of you who look to read other people's pull requests to see what they did, let this be a message to you: 

Please run "mage runprecommit" first before a push LOL. It will save you time.

**Comment by l50** [comment]
> For those of you, like me, who read other people's pull requests to see what they did, let this be a message to you:
> 
> Please run "mage runprecommit" first before a push LOL. It will save you time.

What he said!

**Review by l50 — APPROVED** [review]
Thank you so much for creating this TTP, we're very excited to add it to the ForgeArmory!

**Pull request merged**
