### PR TITLE
Refinement and Documentation of macOS TTPs

### PR DESCRIPTION
**Pull request by l50**
I accidentally hosed https://github.com/facebookincubator/ForgeArmory/pull/37, so here's a new one:

# Proposed Changes

- Move macOS TTPs into relevant directories
- Create docs for every macOS TTP
- Add arguments to macOS TTPs (where needed)
- Bug fixes

## Related Issue(s)

N/A

## Testing

Every TTP was run after changes were made.

## Documentation

Added README to every macOS TTP

## Screenshots/GIFs (optional)

N/A

## Checklist

- [x] Ran `mage runprecommit` locally and fixed any issues that arose.
- [x] Curated your commit(s) so they are legible and easy to read and understand.
- [x] 🚀

### CODE REVIEW

**Review by d3sch41n — CHANGES_REQUESTED** [review]
We have native builtin support for cleanup execution that is composable with `ttp:`, LIFO, and can be disabled as needed with `--no-cleanup` - what's the issue that requires re-implementing it with args? 

image

**Comment by l50** [comment]
> We have native builtin support for cleanup execution that is composable with `ttp:`, LIFO, and can be disabled as needed with `--no-cleanup` - what's the issue that requires re-implementing it with args?

Good call, I didn't remember we had that option. I'll update the PR.

**Comment by l50** [comment]
Synced this PR with upstream to fix the merge conflicts.

**Comment by d3sch41n** [comment]
cool cool - ok I'm gonna punt to @cedowens for final review since it's his TTP suite

**Review by cedowens — APPROVED** [review]
tested and LGTM!

**Review by cedowens — APPROVED** [review]
Tested and LGTM!

**Pull request merged**
